//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressStore.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DressStore.Api.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Kategori oluşturuldu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryCreated {
            get {
                return ResourceManager.GetString("CategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori bulundu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryFound {
            get {
                return ResourceManager.GetString("CategoryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori adı girmek zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori adı çok uzun. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryNameTooLong {
            get {
                return ResourceManager.GetString("CategoryNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori adı çok kısa. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryNameTooShort {
            get {
                return ResourceManager.GetString("CategoryNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryUpdated {
            get {
                return ResourceManager.GetString("CategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renk sadece harf içerebilir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ColorFormatInvalid {
            get {
                return ResourceManager.GetString("ColorFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renk gereklidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ColorRequired {
            get {
                return ResourceManager.GetString("ColorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açıklama en fazla 1000 karakterden oluşabilir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz e-mail formatı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EmailFormatInvalid {
            get {
                return ResourceManager.GetString("EmailFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-mail gereklidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem başarısız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem başarılı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GenericSuccess {
            get {
                return ResourceManager.GetString("GenericSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz görsel URL&apos;si. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageUrlInvalid {
            get {
                return ResourceManager.GetString("ImageUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görsel URL&apos;si zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageUrlRequired {
            get {
                return ResourceManager.GetString("ImageUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad &quot;ğ&quot; harfiyle başlayamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NameCannotStartsWithGh {
            get {
                return ResourceManager.GetString("NameCannotStartsWithGh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad büyük harf ile başlamak zorunda. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NameMustStartWithUppercase {
            get {
                return ResourceManager.GetString("NameMustStartWithUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şehir adı boş bırakılamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem başarılı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiyat negatif olamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PriceCannotBeNegative {
            get {
                return ResourceManager.GetString("PriceCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün oluşturuldu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductCreated {
            get {
                return ResourceManager.GetString("ProductCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductDeleted {
            get {
                return ResourceManager.GetString("ProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün bulundu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductFound {
            get {
                return ResourceManager.GetString("ProductFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün görseli eklendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductImageCreated {
            get {
                return ResourceManager.GetString("ProductImageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün görseli silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductImageDeleted {
            get {
                return ResourceManager.GetString("ProductImageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün görseli bulundu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductImageFound {
            get {
                return ResourceManager.GetString("ProductImageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün görseli bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductImageNotFound {
            get {
                return ResourceManager.GetString("ProductImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün görseli güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductImageUpdated {
            get {
                return ResourceManager.GetString("ProductImageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün adı girmek zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün adı çok uzun. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductNameTooLong {
            get {
                return ResourceManager.GetString("ProductNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün adı çok kısa. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductNameTooShort {
            get {
                return ResourceManager.GetString("ProductNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün güncellendi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductUpdated {
            get {
                return ResourceManager.GetString("ProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürünün varyantı silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductVariantDeleted {
            get {
                return ResourceManager.GetString("ProductVariantDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürünün varyantı bulundu. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductVariantFound {
            get {
                return ResourceManager.GetString("ProductVariantFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz beden (XS, S, M, L, XL, XXL, XXXL olmalı) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SizeInvalid {
            get {
                return ResourceManager.GetString("SizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beden bilgisi gereklidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SizeRequired {
            get {
                return ResourceManager.GetString("SizeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU formatı geçersiz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SkuFormatInvalid {
            get {
                return ResourceManager.GetString("SkuFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU alanı zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SkuRequired {
            get {
                return ResourceManager.GetString("SkuRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slug sadece küçük harf, rakam ve tire içerebilir. Lütfen tekrar deneyin. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlugFormatInvalid {
            get {
                return ResourceManager.GetString("SlugFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slug gereklidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlugRequired {
            get {
                return ResourceManager.GetString("SlugRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slug en az 3 karakterden oluşmalıdır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlugTooShort {
            get {
                return ResourceManager.GetString("SlugTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stok negatif olamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StockCannotBeNegative {
            get {
                return ResourceManager.GetString("StockCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama hatası. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama başarılı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ValidationSuccessful {
            get {
                return ResourceManager.GetString("ValidationSuccessful", resourceCulture);
            }
        }
    }
}
