//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressStore.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DressStore.Api.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Kategori adı girmek zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori adı çok uzun. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryNameTooLong {
            get {
                return ResourceManager.GetString("CategoryNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori adı çok kısa. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CategoryNameTooShort {
            get {
                return ResourceManager.GetString("CategoryNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz görsel URL&apos;si. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageUrlInvalid {
            get {
                return ResourceManager.GetString("ImageUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görsel URL&apos;si zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageUrlRequired {
            get {
                return ResourceManager.GetString("ImageUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad &quot;ğ&quot; harfiyle başlayamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NameCannotStartsWithGh {
            get {
                return ResourceManager.GetString("NameCannotStartsWithGh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad büyük harf ile başlamak zorunda. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NameMustStartWithUppercase {
            get {
                return ResourceManager.GetString("NameMustStartWithUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şehir adı boş bırakılamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiyat negatif olamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PriceCannotBeNegative {
            get {
                return ResourceManager.GetString("PriceCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün adı girmek zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün adı çok uzun. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductNameTooLong {
            get {
                return ResourceManager.GetString("ProductNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün adı çok kısa. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProductNameTooShort {
            get {
                return ResourceManager.GetString("ProductNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU formatı geçersiz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SkuFormatInvalid {
            get {
                return ResourceManager.GetString("SkuFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKU alanı zorunludur. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SkuRequired {
            get {
                return ResourceManager.GetString("SkuRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stok negatif olamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StockCannotBeNegative {
            get {
                return ResourceManager.GetString("StockCannotBeNegative", resourceCulture);
            }
        }
    }
}
